### ISSUE TITLE
UI: Верстка экрана поиска (без поискового запроса)

### ISSUE THREAD

**Issue by val-hero** [val-hero/AtYourService#24]
Сверстать экран поиска - Search (main) на макете, без логики.
Экран состоит из нескольких частей:
- Первая - это шапка с профилем, выбором города и строкой поиска. Она будет видна на всех экранах поиска:
![image](https://github.com/val-hero/At-Your-Service/assets/116488693/18e5dc94-4450-489d-9779-fe5757ab09f2)

- Вторая - это контейнер для вложенного фрагмента, содержимое которого будет меняться: 
![image](https://github.com/val-hero/At-Your-Service/assets/116488693/f26def48-1b15-49ec-a4a5-f1cd74a8cef2)

Вторая часть состоит из нескольких списков: 
- Popular Companies - горизонтальный список с 3 элементами. (тут можно ограничиться listview или scrollview, список не будет расширяться)
- Categories - горизонтальный список с N элементов, тут их может быть много.
- Top rated experts - вертикальный список из 15 элементов, карточка эксперта для этого списка уже создана

Экран нужно наполнить любыми mock-данными

**Comment by val-hero** [comment]
P.S. Над задачей можно работать совместно, например, подготовить нужные recycler'ы и части экрана, а потом слепить их вместе. Для этого удобно будет сделать одну основную ветку и разные доп.ветки из неё, заливая PR в основную

**Comment by menta1** [comment]
Popular Companies - горизонтальный список с 3 элементами, нужно установить радиус и цвет линии радиуса
