### ISSUE TITLE
Feat: Создать стилизованный диалог для экрана Forgot Password

### ISSUE THREAD

**Issue by val-hero** [val-hero/AtYourService#5]
Задача доступна после закрытия: #4 

Сделать верстку диалога по дизайну (Forgot Password на макете), который показывается на экране Authorization при нажатии на текст "Forgot password?" (Забыли пароль?) и привязать его отображение к нажатию на этот текст.

**Comment by manualcheg** [comment]
Вроде сделал.
Жду готовности задачи 4.

**Comment by val-hero** [comment]
> Вроде сделал. Жду готовности задачи 4.

Можешь сразу кидать PR на ревью

**Comment by manualcheg** [comment]
Во фрагменте авторизации добавить код вызова диалога. Примерно такой:

binding.buttonGetDialog.setOnClickListener {
            val myResetpassDialogFragment = ResetpassDialogFragment()
            val manager = parentFragmentManager
            myResetpassDialogFragment.show(manager, "myDialog")
        }

**Comment by manualcheg** [comment]
Всё реализовано и добавлено в ветку dev
